export const API_URL:string = "https://secret-lake-26389.herokuapp.com"
export const AUTH_TOKEN:String="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MzQxNzQ0NjcsImV4cCI6MTUzNjc2NjQ2N30.ZXKR_Rz18E40yRvK3ln5lkVkhdamuSf6-W7JO3nnD1I"
export const CHECK_PATH:string="/checks"
export const BUSINESS_PATH:string="/businesses"
export const MENUITEMS_PATH:string="/menuItems"
export const ORDERED_ITEMS_PATH:string="/orderedItems"
export const LABOR_PATH:string='/laborEntries'
export const EMPLOYEE_PATH:string='/employees'
export const MS_IN_HOUR:number=3600000
export const MS_IN_DAY:number=86400000
export const CONNECTION_TIMEOUT_LENGTH:number=45000